closeio/tasktiger

- README.rst
- tasktiger/__init__.py
- tasktiger/_internal.py
- tasktiger/exceptions.py
- tasktiger/worker.py
- tests/__init__.py
- tests/tasks.py
> More flexible retrying using RetryException

- README.rst
- tasktiger/__init__.py
- tasktiger/rollbar.py
Also adds setup_structlog param to quickly create TaskTiger worker scripts without having to deal with structlog.
> Rollbar integration

- README.rst
- tasktiger/flask_script.py
Seamless `flask-script` integration, which also ensures that tasks have access to the application contest (via `flask-script`)
> flask_script integration

- README.rst
> Docs improvements

- README.rst
- tasktiger/__init__.py
- tasktiger/_internal.py
- tasktiger/task.py
- tasktiger/worker.py
- tests/__init__.py
- tests/tasks.py
Ability to access the current task object from within the task function using `tiger.current_task` (or `tiger.current_tasks` in case of a batch function).
> Ability to access the current task object from within the task function

- tasktiger/_internal.py
- tasktiger/stats.py
- tasktiger/worker.py
> Prevent possible deadlock for tasks that use logging

- tasktiger/__init__.py
keep the behave same as `TaskTiger.delay`
> return delay task

- tasktiger/lua/execute_pipeline.lua
- tasktiger/redis_scripts.py
- tasktiger/task.py
- tests/test_base.py
- tests/test_redis_scripts.py
@closeio/engineering feel free to review
> Redis script to allow abortable pipelines (fixes #54)

- tasktiger/__init__.py
- tasktiger/stats.py
- tasktiger/worker.py
- tests/tasks.py
- tests/tasks_periodic.py
- tests/test_base.py
- tests/test_periodic.py
- tests/utils.py
Reduces Redis activity by:
1. Support lockable queues to prevent multiple workers from processing the same queue
1. Sleep when possible between worker loop execution
> Improve redis usage

- tasktiger/worker.py
> fix: structlog-exception-api

- tests/test_base.py
This should fix the race condition in that test that caused it to fail sometimes.
> Shorten sleep for swq test

- README.rst
Does this clarification make sense?
> Clarify what happens when requeueing a unique task

- .circleci/config.yml
- pyproject.toml
- setup.py
- tasktiger/__init__.py
- tasktiger/_internal.py
- tasktiger/exceptions.py
- tasktiger/flask_script.py
- tasktiger/redis_lock.py
- tasktiger/redis_scripts.py
- tasktiger/redis_semaphore.py
- tasktiger/retry.py
- tasktiger/rollbar.py
- tasktiger/schedule.py
- tasktiger/stats.py
- tasktiger/task.py
- tasktiger/test_helpers.py
- tasktiger/timeouts.py
- tasktiger/worker.py
- tests/tasks.py
- tests/test_base.py
- tests/test_context_manager.py
- tests/test_periodic.py
- tests/test_queue_size.py
- tests/test_redis_scripts.py
- tests/test_semaphore.py
- tests/test_workers.py
- tests/utils.py
This change applies and enforces code formatting with the [`black`](https://github.com/psf/black) tool.
The formatting settings are consistent with the settings used in other `closeio` projects.
> Apply and enforce black formatting

- tasktiger/task.py
- tests/test_task.py
> Ensure task exists in the given queue when retrieving it

- README.rst
Documenting what I did to release 0.12 and 0.13.
> Document release process

- tasktiger/task.py
Needed for https://github.com/closeio/tasktiger-admin/pull/22
btw. where could I find some notes about release process of this lib?
> Add Task.time_last_queued

- tasktiger/task.py
Needed for https://github.com/closeio/tasktiger-admin/pull/23
> Populate Task.ts field in Task.from_id fn

- tasktiger/tasktiger.py
Closes https://github.com/closeio/tasktiger/issues/178
> Add TaskTiger.would_process_configured_queue

- .circleci/config.yml
- .github/workflows/test.yaml
With some dependencies upgraded, tests now run on 3.10
> Run tests on 3.10

- CHANGELOG.md
- setup.py
Breaking changes:
- https://github.com/closeio/tasktiger/pull/251
- https://github.com/closeio/tasktiger/pull/258
> Bump version to 0.17.0

- .gitignore
- setup.cfg
- tasktiger/_internal.py
- tasktiger/exceptions.py
- tasktiger/flask_script.py
- tasktiger/logging.py
- tasktiger/migrations.py
- tasktiger/redis_scripts.py
- tasktiger/redis_semaphore.py
- tasktiger/retry.py
- tasktiger/rollbar.py
- tasktiger/runner.py
- tasktiger/schedule.py
- tasktiger/stats.py
- tasktiger/task.py
- tasktiger/tasktiger.py
- tasktiger/test_helpers.py
- tasktiger/timeouts.py
- tasktiger/types.py
- tasktiger/utils.py
- tasktiger/worker.py
> Add types to everything

- CHANGELOG.md
- setup.py
will only release once tested in production
> Release 0.18

- CHANGELOG.md
- setup.py
includes https://github.com/closeio/tasktiger/pull/296
> release 0.18.1

- CHANGELOG.md
- tasktiger/__init__.py
- tasktiger/tasktiger.py
- tests/test_queue_size.py
Lets us query specific queue sizes in a single Redis round trip.
> Get sizes for queues and states
